server.port=${SERVER_PORT:3000}

quarkus.api.base-url=${QUARKUS_API_BASE_URL:http://localhost:8081}
quarkus.api.connect-timeout-ms=${QUARKUS_API_CONNECT_TIMEOUT_MS:3000}
quarkus.api.read-timeout-ms=${QUARKUS_API_READ_TIMEOUT_MS:5000}

logging.level.root=INFO
