quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=appuser
quarkus.datasource.password=apppass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/personasdb?options=-c%20TimeZone%3DUTC
quarkus.datasource.devservices.enabled=false

quarkus.http.port=8081
quarkus.http.cors=true

quarkus.log.level=INFO

quarkus.hibernate-orm.database.generation=update
